# Generated by Django 5.2.4 on 2025-07-14 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_choices_question_quiz_user_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.quiz'),
            preserve_default=False,
        ),
    ]
