# Generated by Django 5.2.4 on 2025-07-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_choices_question_quiz_user_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='question',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_number',
        ),
    ]
