# Generated by Django 5.2.4 on 2025-07-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_user_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
