# Generated by Django 5.2.4 on 2025-07-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_choices_question_quiz_user_delete_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='choice_number',
        ),
        migrations.AlterField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
