# Generated by Django 5.2.4 on 2025-07-14 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_question_quiz_q'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='q',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choices',
            name='choice_number',
            field=models.IntegerField(default=0),
        ),
    ]
