# Generated by Django 5.2.4 on 2025-07-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_choices_choice_number_alter_choices_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choice_text',
            field=models.CharField(max_length=150),
        ),
    ]
