# Generated by Django 5.2.4 on 2025-07-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_question_quiz_number_remove_quiz_quiz_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='number',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', to='api.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
