# Generated by Django 5.2.4 on 2025-07-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_choice_question_delete_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_text',
        ),
    ]
