# Generated by Django 5.2.4 on 2025-07-08 16:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quiz_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_number',
            field=models.ForeignKey(blank=True,null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.quiz'),
            preserve_default=False,
        ),
    ]
