# Generated by Django 5.2.4 on 2025-07-08 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_quiz_question_quiz_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz_number',
            new_name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_number',
        ),
        migrations.AddField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choices',
            name='choice_text',
            field=models.CharField(max_length=150),
        ),
    ]
