# Generated by Django 5.2.4 on 2025-07-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_quiz_number_question_quiz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='quiz_number',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_code',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='choices',
            name='choice_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='choices',
            name='choice_text',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
