# Generated by Django 5.2.4 on 2025-07-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_quiz_question_quiz_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz_number',
            new_name='quiz',
        ),
    ]
