# Generated by Django 5.2.4 on 2025-07-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_quiz_question_quiz_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choice_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
